### ISSUE TITLE
実行時に最適化設定を .toml から読めるようにする

### ISSUE THREAD

**Issue by usagi** [usagi/VReducer#1]
この機能追加により、ユーザーは .toml に何をどう最適化するか、設定変更するかについて細かく設定できるようにします。たぶん。

何をどう書くか、 .toml の構造は未定。作業時間とれたらこの issue に中間状態について書くかもしれません。

- [x] .toml の設計
- [x] experimental-runtime-conf ブランチで実装
- [ ] master へ merge
- [ ] 本家版への PR (optional)

---

だいたい↓ https://github.com/usagi/VReducer/blob/30c7d2f7ea544349590a93b99238ece951ab2baa/vrm/reducer.py#L594 の何をやるかのカスタムをできるようにする。

**Comment by usagi** [comment]
```toml
[feature]
deduplicated-materials = true
combine-all-primitives = true
shrink-materials = true
sort-face-primitives = true
combine-materials = true
replace-shade-color = true
emissive-color = true
texture-size = [ 2048, 2048 ]
force = false

# ↓materialを定義すると combine-materials が true の場合のマテリアルに関する
# 動作をユーザー独自に設定できます。↓materialを定義せずに実行した場合は、
# VReducer内蔵の設定と服の推論による従来通りの動作になります。

# 独自のテクスチャー、素体、服などを使用した VRM に対して使用したい場合や、
# VRoid Studio の 更新があり VReducer の内蔵定義が追いついていない場合に便利かもしれません。

# 以下はユーザー定義は STUDENT タイプの服のモデルに対する内蔵定義と同様の動作を
# ユーザーの独自定義で与える場合の例です。

# Note: TOMLの構造をツリー構造で見たり、JSONやYAMLと比較してみたい場合は
# https://toolkit.site/format.html
# とか使うと幸せになれるかもしれません。

# 制服上下、リボン、靴
[[material.resize_info.baseColorTexture]]
key  = "baseColorTexture"
pos  = [    0,    0 ]
size = [ 2048, 2536 ]
[[material.resize_info.baseColorTexture]]
key  = "baseColorTexture"
pos  = [    0, 1536 ]
size = [  512,  512 ]
[[material.resize_info.baseColorTexture]]
key  = "baseColorTexture"
pos  = [  512, 1536 ]
size = [  512,  512 ]
[[material.resize_info.baseColorTexture]]
key  = "baseColorTexture"
pos  = [ 1024, 1536 ]
size = [  512,  512 ]
# 体、顔、口
[[material.resize_info._Face_]]
key  = '_Face_'
pos  = [    0,    0 ]
size = [  512,  512 ]
[[material.resize_info._Face_]]
key  = '_Face_'
pos  = [    0,    0 ]
size = [  512,  512 ]
[[material.resize_info._Face_]]
key  = '_Face_'
pos  = [    0,    0 ]
size = [  512,  512 ]
[[material.resize_info._Face_]]
key  = '_FaceMouth_'
pos  = [  512,    0 ]
size = [  512,  512 ]
[[material.resize_info._Face_]]
key  = '_Body_'
pos  = [    0,  512 ]
size = [ 2048, 1536 ]
# アイライン、まつ毛
[[material.resize_info._FaceEyeline_]]
key  = '_FaceEyeline_'
pos  = [    0,  512 ]
size = [ 1024,  512 ]
[[material.resize_info._FaceEyeline_]]
key  = '_FaceEyelash_'
pos  = [    0, 1024 ]
size = [ 1024,  512 ]
# 瞳孔、ハイライト、白目
[[material.resize_info._EyeHighlight_]]
key  = '_EyeIris_'
pos  = [    0,    0 ]
size = [ 1024,  512 ]
[[material.resize_info._EyeHighlight_]]
key  = '_EyeHighlight_'
pos  = [    0,  512 ]
size = [ 1024,  512 ]
[[material.resize_info._EyeHighlight_]]
key  = '_EyeWhite_'
pos  = [    0, 1024 ]
size = [ 1024,  512 ]
# 髪の毛、頭の下毛
[material.resize_info._Hair_]
key  = '_Hair_'
pos  = [    0,    0 ]
size = [  512, 1024 ]
# ↓to_name を true にするとテーブル名(↑material.resize_info._Hair_の_Hair_)で
# find した結果、取得できたマテリアルの `name` 値を統合先の名前として採用します。
to_name = true
# ↓こうすると _hair_Back_ は _Hair_ と一緒に処理されます
[[material.resize_info._Hair_._HairBack_]]
key  = '_HairBack_'
pos  = [  512,    0 ]
size = [ 1024, 1024 ]

# material.modify を定義すると特定のマテリアルのパラメーターを変更できます
# ↓は本体内蔵機能でも対応しているレンダータイプの変更を行う場合の例です
[material.modify._Face_.keywordMap]
_ALPHATEST_ON = true
[material.modify._Face_.tagMap]
RenderType = "TransparentCutout"

```

**Comment by usagi** [comment]
ニーズがあるようだしはやいことやろうかと思ってコードを確認して気づいたんだ:

https://github.com/zk-phi/VReducer/commit/e26efc541e47dbb1c7402b66d9c0a87c31814725

このパッチ、 + だと思い込んで merge しちゃったんだけど - だった😅 なるほど、理解した☠

**Comment by usagi** [comment]
ま、このissue実装したらそれも含めて大丈夫みんなHappyになるから問題ないね👍

**Comment by usagi** [comment]
`feature`はそもそも command line で指定できるので conf 対応するメリットがあまり高くない。寧ろユーザビリティーとして同じ設定を複数の方法でできる状況は混乱と複雑さを増加するためよくない。 TOML の conf は material についてのみに特化することにしましょう。

**Comment by usagi** [comment]
```python
            gltf = combine_material(gltf, {
                'baseColorTexture': {'pos': (0, 0), 'size': (2048, 1536)},
                'baseColorTexture': {'pos': (0, 1536), 'size': (512, 512)},
                'baseColorTexture': {'pos': (512, 1536), 'size': (512, 512)},
                'baseColorTexture': {'pos': (1024, 1536), 'size': (512, 512)}
            }, 'baseColorTexture', texture_size)
```

オリジナルのコードのこういうとこの `{}` で dict 作って `combine_material` へ渡してるコード、 dict の定義が実は `[ { }, ... ]`が正しい不具合かな？あるいは何か意図して冗長なハードコードをしている？

pythonでは同じキーで複数並べた dict リテラルの評価結果は最後に評価されたキーしか入らないようだし、 multimap 的なキー重複 dict は少なくとも dict そのものの機能には無いと思うので、なんだろうか？

**Comment by usagi** [comment]
ほそく:

```python
{
                'baseColorTexture': {'pos': (0, 0), 'size': (2048, 1536)},
                'baseColorTexture': {'pos': (0, 1536), 'size': (512, 512)},
                'baseColorTexture': {'pos': (512, 1536), 'size': (512, 512)},
                'baseColorTexture': {'pos': (1024, 1536), 'size': (512, 512)}
            }
```

の python での評価結果は

```python
{ 'baseColorTexture': {'pos': (1024, 1536), 'size': (512, 512)} }
```

と同じになる。

**Comment by usagi** [comment]
ぁー、オリジナルのコードではここは↑のようにはなっていなかったんだ:

https://github.com/kanno2inf/VReducer/blob/master/vrm/reducer.py#L627

で、

https://github.com/nkjzm/VReducer/commit/455400a2d93c944e8ad7daddd0cbfd493bd9fa42

↑これでこうなってる。とりあえず0.8.3対応ということらしかったしVRMの仕様もPythonもよくしらんのでmergeして（必要なら後でどうにかしよー的な）しまったのだけど、これは…もしかして何かおかしいのでは？

**Comment by usagi** [comment]
VRMのデータ構造とかBlenderとかある程度わかった後のわたし的には、とりあえず VRoid Studio 0.8.3 で作成した VRM のマテリアル名を確認してみた:

![image](https://user-images.githubusercontent.com/115972/79346443-599f5b00-7f6d-11ea-8180-f60534c8245b.png)

ここは VRM から import しただけで名前は変わってはいないだろうし、このパッチやっぱり何かがおかしいのでは…

**Comment by usagi** [comment]
これは…revert というか、私のPython3対応のPRも本家ではその後Mergeしてもらっているし、本家/masterを-fでうちのmasterにもいったん上書きしちゃって、そこを base に本件開発してまた本家PRでいいかな。

**Comment by usagi** [comment]
だめですね、ちゃんとソースのdiffも読んでから取り込まないと。そもそも本家へのPRが出されてない時点で気づくべきだったか。うぐぐ。とりま、私の中では解決したのでOK、進みましょう！

**Comment by usagi** [comment]
`_Hair_` のところが2段階になってるところをどうしようか思案するための確認:

https://github.com/kanno2inf/VReducer/blob/5d72e2696978f593321ed7f133977addfa466f58/vrm/reducer.py#L412

↑のように `combine_material` の内部でも `resize_info` パラメーターで渡った key は `find_vrm_material` を噛んでいる。なので、↓

https://github.com/kanno2inf/VReducer/blob/5d72e2696978f593321ed7f133977addfa466f58/vrm/reducer.py#L681

髪の毛のところで `_HairBack_` を key で入れてもそれもちゃんと `combine_material` の内部で `find_vrm_material` されて具体的なデータ内部でのkeyになってる↓

![image](https://user-images.githubusercontent.com/115972/79351064-311a5f80-7f73-11ea-84f3-a4aa27712cda.png)

**Comment by usagi** [comment]
と、いうわけで、 TOML の設計全体をリニューアル:

```toml
# ↓materialを定義すると combine-materials が true の場合のマテリアルに関する
# 動作をユーザー独自に設定できます。↓materialを定義せずに実行した場合は、
# VReducer内蔵の設定と服の推論による従来通りの動作になります。

# 独自のテクスチャー、素体、服などを使用した VRM に対して使用したい場合や、
# VRoid Studio の 更新があり VReducer の内蔵定義が追いついていない場合に便利かもしれません。

# 以下はユーザー定義は STUDENT タイプの服のモデルに対する内蔵定義と同様の動作を
# ユーザーの独自定義で与える場合の例です。

# Note: TOMLの構造をツリー構造で見たり、JSONやYAMLと比較してみたい場合は
# https://toolkit.site/format.html
# とか使うと幸せになれるかもしれません。

# 制服上下、リボン、靴
[material.resize_info._Tops_._Tops_]
pos  = [    0,    0 ]
size = [ 2048, 2536 ]
[material.resize_info._Tops_._Bottoms_]
pos  = [    0, 1536 ]
size = [  512,  512 ]
[material.resize_info._Tops_._Accessory_]
pos  = [  512, 1536 ]
size = [  512,  512 ]
[material.resize_info._Tops_._Shoes_]
pos  = [ 1024, 1536 ]
size = [  512,  512 ]

# 体、顔、口
[material.resize_info._Face_._Face_]
pos  = [    0,    0 ]
size = [  512,  512 ]
[material.resize_info._Face_._FaceMouth_]
pos  = [  512,    0 ]
size = [  512,  512 ]
[material.resize_info._Face_._Body_]
pos  = [    0,  512 ]
size = [ 2048, 1536 ]

# アイライン、まつ毛
[material.resize_info._FaceEyeline_._FaceEyeline_]
pos  = [    0,  512 ]
size = [ 1024,  512 ]
[material.resize_info._FaceEyeline_._FaceEyelash_]
pos  = [    0, 1024 ]
size = [ 1024,  512 ]

# 瞳孔、ハイライト、白目
[material.resize_info._EyeHighlight_._EyeIris_]
pos  = [    0,    0 ]
size = [ 1024,  512 ]
[material.resize_info._EyeHighlight_._EyeHighlight_]
pos  = [    0,  512 ]
size = [ 1024,  512 ]
[material.resize_info._EyeHighlight_._EyeWhite_]
pos  = [    0, 1024 ]
size = [ 1024,  512 ]

# ↓のように resize_info_near をテーブルを使うと、
# 1. _HairBack_ (=TOMLのテーブル名)に "部分一致" するマテリアル(*1)を探し、
# 2. (*1)_と色の近い _Hair_ (=near_key)に "部分一致" するマテリアル(*2)を探し、
# 3. (*1) を pos, size 、(*2) を near_pos, near_size で_(*2) へ統合
# します。

# 髪の毛、頭の下毛
[material.resize_info_near._HairBack_]
pos  = [  512,    0 ]
size = [ 1024, 1024 ]
near_key = "_Hair_"
near_pos  = [    0,    0 ]
near_size = [  512, 1024 ]

# material.modify を定義すると特定のマテリアルのパラメーターを変更できます
# ↓は本体内蔵機能でも対応しているレンダータイプの変更を行う場合の例です
[material.modify._Face_.keywordMap]
_ALPHATEST_ON = true
[material.modify._Face_.tagMap]
RenderType = "TransparentCutout"
```

**Comment by usagi** [comment]
とりあえずできた https://github.com/usagi/VReducer/tree/experimental-conf-feature

**Comment by usagi** [comment]
VRoid Studio 標準の Sendagaya Shino の VRM そのままのマテリアル群↓

![image](https://user-images.githubusercontent.com/115972/79367573-1226c800-7f89-11ea-8675-cac030a9b0b1.png)

VReducer 内蔵定義で統合したマテリアル群↓

![image](https://user-images.githubusercontent.com/115972/79367770-5f0a9e80-7f89-11ea-8777-aedf4d8c6339.png)

conf の同等設定で統合したマテリアル群↓

![image](https://user-images.githubusercontent.com/115972/79368120-de986d80-7f89-11ea-861a-8307a3bb8d77.png)

`EyeExtra` の統合機能が conf に未実装だったようだ。追加しましょう。

**Comment by usagi** [comment]
妙な機能追加で conf 定義が複雑になるより、↓のように conf 使うなら conf にマテリアル書けばいいんじゃないかな、と発想を変えました。

```toml
# アイライン、まつ毛
[material.resize_info._FaceEyeline_._EyeExtra_]
pos  = [    0,  512 ]
size = [ 1024,  512 ]
[material.resize_info._FaceEyeline_._FaceEyeline_]
pos  = [    0,  512 ]
size = [ 1024,  512 ]
[material.resize_info._FaceEyeline_._FaceEyelash_]
pos  = [    0, 1024 ]
size = [ 1024,  512 ]
```
